#!/bin/sh
LOGANALYSIS_HOME=/home/webadmin/loganalysis
JAVA_HOME=/usr/local/java/jdk
CLASSPATH=.
CLASSPATH=$CLASSPATH:$LOGANALYSIS_HOME/libs/activation-1.1.jar
CLASSPATH=$CLASSPATH:$LOGANALYSIS_HOME/libs/ant-1.8.3.jar
CLASSPATH=$CLASSPATH:$LOGANALYSIS_HOME/libs/ant-javamail-1.8.3.jar
CLASSPATH=$CLASSPATH:$LOGANALYSIS_HOME/libs/ant-launcher-1.8.3.jar
CLASSPATH=$CLASSPATH:$LOGANALYSIS_HOME/libs/asm-3.3.1.jar
CLASSPATH=$CLASSPATH:$LOGANALYSIS_HOME/libs/cglib-2.2.2.jar
CLASSPATH=$CLASSPATH:$LOGANALYSIS_HOME/libs/commons-beanutils-1.8.3.jar
CLASSPATH=$CLASSPATH:$LOGANALYSIS_HOME/libs/commons-codec-1.5.jar
CLASSPATH=$CLASSPATH:$LOGANALYSIS_HOME/libs/commons-digester3-3.2.jar
CLASSPATH=$CLASSPATH:$LOGANALYSIS_HOME/libs/commons-jexl-2.1.1.jar
CLASSPATH=$CLASSPATH:$LOGANALYSIS_HOME/libs/commons-logging-1.1.1.jar
CLASSPATH=$CLASSPATH:$LOGANALYSIS_HOME/libs/junit-3.8.1.jar
CLASSPATH=$CLASSPATH:$LOGANALYSIS_HOME/libs/log4j-1.2.14.jar
CLASSPATH=$CLASSPATH:$LOGANALYSIS_HOME/libs/loganalysis-1.2.jar
CLASSPATH=$CLASSPATH:$LOGANALYSIS_HOME/libs/mail-1.4.5.jar
CLASSPATH=$CLASSPATH:$LOGANALYSIS_HOME/libs/poi-3.8.jar

cd $LOGANALYSIS_HOME

$JAVA_HOME/bin/java -Dsend.mail.script=sendmail.xml -Dperl.path=/usr/bin/perl -Dloganalysis.home=$LOGANALYSIS_HOME -cp $CLASSPATH com.changyou.loganalysis.LogAnalysisMain $1 $2 $3 $4

